### ISSUE TITLE
ARM64 cross compilation targets missing

### ISSUE THREAD

**Issue by jmacato** [flathub/org.freedesktop.Sdk.Extension.llvm16#11]
Seems like this SDK extension doesnt support `aarch64-unknown-linux-gnu` nor `arm64-apple-darwin` as targets while vanilla LLVM16 does.

**Comment by hfiguiere** [comment]
there is no cross-compilation on flathub. it will use the aarch64 hosted on aarch64.

**Comment by jmacato** [comment]
Ahh that's too bad... Seems like this is unfixable then.

**Comment by hfiguiere** [comment]
it's not like you explained what you wanted to do either.
